---
# https://github.com/actions/starter-workflows/blob/main/ci/maven.yml
name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for main
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: task clean check build
      run: task clean check build

    - name: find . -name "*.xml"
      run: find . -name "*.xml"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cmem-jena-http-client JAR
        path: cmem-jena-http-client/target/*.jar
