---
# https://github.com/actions/starter-workflows/blob/main/ci/maven.yml
name: ci

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: task clean check build
      run: task clean check build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cmem-jena-http-client JAR
        path: cmem-jena-http-client/target/*.jar
